# Generated by Django 2.0.4 on 2018-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_stat',
            field=models.CharField(choices=[('av', ' Available'), ('un', 'Unavailable')], default='av', max_length=2),
        ),
    ]
